on:
  push:
     branches:
       - main
  pull_request:
     branches:
       - main

name: renderbook

jobs:
  bookdown:
    name: setup tinytex
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.3'
      - name: Install tinytex
        run: install.packages("tinytex")
        shell: Rscript {0}
      - name: Get R and OS version
        id: get-version
        run: |
          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
        shell: Rscript {0}
      - name: Restore TinyTex cache
        uses: actions/cache@v2
        id: tinytex-cache
        with:
          path: |
            ~/.TinyTeX
            ~/bin
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-4-1

      - name: install TinyTex
        if: steps.tinytex-cache.outputs.cache-hit != 'true'
        run:  tinytex::install_tinytex()
        shell: Rscript {0}
